# Wordle Rust プロジェクト - rustfmt 設定
# モダンなRustコーディングのベストプラクティスに基づく設定

# 基本設定
edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4

# インポート設定
reorder_imports = true
reorder_modules = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# 関数とメソッド設定
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
where_single_line = false

# 構造体と列挙型設定
struct_lit_single_line = true
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_block_trailing_comma = false

# コメント設定
normalize_comments = false
wrap_comments = false
format_doc_comments = false
comment_width = 80

# 文字列設定
format_strings = false
format_macro_matchers = true
format_macro_bodies = true

# 配列とスライス設定
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50

# その他の設定
remove_nested_parens = true
use_small_heuristics = "Default"
binop_separator = "Front"
combine_control_expr = true
condense_wildcard_suffixes = false
force_explicit_abi = true
format_generated_files = true
hex_literal_case = "Preserve"
hide_parse_errors = false
ignore = []
license_template_path = ""
merge_derives = true
newline_style = "Auto"
normalize_doc_attributes = false
overflow_delimited_expr = false
remove_blank_lines_at_start_or_end_of_block = true
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
type_punctuation_density = "Wide"
unstable_features = false
use_field_init_shorthand = false
use_try_shorthand = false
version = "Two"
